# Priority: Post-processed (p/red) > Standard > Script-specific
EPITRAN_LANG_MAP = {
    "afar": "aar-Latn",
    "afrikaans": "afr-Latn",
    "amharic": "amh-Ethi-pp",
    "arabic": "ara-Arab",
    "assyrian neo-aramaic": "aii-Syrc",
    "avar": "ava-Cyrl",
    "azerbaijani": "aze-Latn",
    "baka": "bxk-Latn",
    "bengali": "ben-Beng-red",
    "bhojpuri": "bho-Deva",
    "burmese": "mya-Mymr",
    "catalan": "cat-Latn",
    "cebuano": "ceb-Latn",
    "chichewa": "nya-Latn",
    "chinese (cantonese)": "yue-Latn",
    "chinese (gan)": "gan-Latn",
    "chinese (hakka)": "hak-Latn",
    "chinese (jin)": "cjy-Latn",
    "chinese (mandarin)": "cmn-Latn",
    "chinese (min nan)": "nan-Latn",
    "chinese (wu)": "wuu-Latn",
    "chinese (xiang)": "hsn-Latn",
    "croatian": "hrv-Latn",
    "czech": "ces-Latn",
    "dutch": "nld-Latn",
    "english": "generic-Latn",
    "esperanto": "epo-Latn",
    "estonian": "est-Latn",
    "farsi": "fas-Arab",
    "finnish": "fin-Latn",
    "french": "fra-Latn-p",
    "frisian": "fry-Latn",
    "fulah": "ful-Latn",
    "galician": "glg-Latn",
    "ganda": "lug-Latn",
    "georgian": "kat-Geor",
    "german": "deu-Latn",
    "gothic": "got-Latn",
    "gujarati": "pan-Guru",
    "haitian creole": "hat-Latn-bab",
    "hausa": "hau-Latn",
    "hindi": "hin-Deva",
    "hmong": "hmn-Latn",
    "hungarian": "hun-Latn",
    "ilocano": "ilo-Latn",
    "indonesian": "ind-Latn",
    "irish": "gle-Latn",
    "italian": "ita-Latn",
    "jamaican patois": "jam-Latn",
    "japanese": "jpn-Hira",
    "javanese": "jav-Latn",
    "kabardian": "kbd-Cyrl",
    "kabyle": "kab-Latn",
    "kannada": "kan-Knda",
    "kazakh": "kaz-Latn",
    "khmer": "khm-Khmr",
    "kinyarwanda": "kin-Latn",
    "korean": "kor-Hang",
    "kurdish (central)": "ckb-Arab",
    "kurdish (kurmanji)": "kmr-Latn",
    "kyrgyz": "kir-Latn",
    "lao": "lao-Laoo",
    "latvian": "lav-Latn",
    "lezgian": "lez-Cyrl",
    "ligurian": "lij-Latn",
    "lithuanian": "lit-Latn",
    "malay": "msa-Latn",
    "malayalam": "mal-Mlym",
    "maltese": "mlt-Latn",
    "maori": "mri-Latn",
    "marathi": "mar-Deva",
    "nahuatl": "nhi-Latn",
    "norwegian": "nno-Latn",
    "occitan": "oci-Latn",
    "oriya": "ori-Orya",
    "oromo": "orm-Latn",
    "pashto": "pbu-Arab",
    "polish": "pol-Latn",
    "portuguese": "por-Latn",
    "punjabi": "pan-Guru",
    "quechua": "quy-Latn",
    "romanian": "ron-Latn",
    "russian": "rus-Cyrl",
    "sango": "sag-Latn",
    "serbian": "srp-Latn",
    "shona": "sna-Latn",
    "sinhala": "sin-Sinh",
    "slovenian": "slv-Latn",
    "somali": "som-Latn",
    "spanish": "spa-Latn",
    "swahili": "swa-Latn",
    "swedish": "swe-Latn",
    "tagalog": "tgl-Latn",
    "tajik": "tgk-Cyrl",
    "tamil": "tam-Taml",
    "telugu": "tel-Telu",
    "thai": "tha-Thai",
    "tigrinya": "tir-Ethi-pp",
    "tswana": "tsn-Latn",
    "turkish": "tur-Latn",
    "turkmen": "tuk-Latn",
    "ukrainian": "ukr-Cyrl",
    "urdu": "urd-Arab",
    "uyghur": "uig-Arab",
    "uzbek": "uzb-Latn",
    "vietnamese": "vie-Latn",
    "xhosa": "xho-Latn",
    "yoruba": "yor-Latn",
    "zhuang": "zha-Latn",
    "zulu": "zul-Latn"
}

ALLOSAURUS_LANG_MAP = {
  "korean": "kor",
  "ket": "ket",
  "lak": "lbe",
  "kabardian": "kbd",
  "georgian": "kat",
  "burushaski": "bsk",
  "kurukh": "kru",
  "telugu": "tel",
  "kota": "kfe",
  "mundari": "unr",
  "kharia": "khr",
  "khasi": "kha",
  "sedang": "sed",
  "cambodian": "khm",
  "vietnamese": "vie",
  "mandarin chinese": "cmn",
  "wu": "wuu",
  "hakka": "hak",
  "cantonese": "yue",
  "yao": "yao",
  "dafla": "njz",
  "burmese": "mya",
  "lahu": "lhu",
  "garo": "grt",
  "karen": "ksw",
  "lakkia": "lbc",
  "thai": "tha",
  "yay": "pcc",
  "cham": "cja",
  "atayal": "tay",
  "malagasy": "plt",
  "malay": "zsm",
  "batak": "bbc",
  "sa'ban": "snv",
  "sundanese": "sun",
  "javanese": "jav",
  "tagalog": "tgl",
  "chamorro": "cha",
  "iai": "iai",
  "kaliai": "khl",
  "adzera": "adz",
  "maori": "mri",
  "hawaiian": "haw",
  "western desert": "ant",
  "nyangumata": "nna",
  "kunjen": "kjn",
  "maranungku": "zmr",
  "maung": "mph",
  "nunggubuyu": "nuy",
  "alawa": "alh",
  "wik-munkan": "wim",
  "sentani": "set",
  "washkuk": "kmo",
  "asmat": "tml",
  "telefol": "tlf",
  "gadsup": "gaj",
  "auyana": "auy",
  "kunimaipa": "kup",
  "selepet": "spl",
  "nasioi": "nas",
  "aleut": "ale",
  "inuit": "kal",
  "chipewyan": "chp",
  "chasta costa": "tol",
  "hupa": "hup",
  "navaho": "nav",
  "haida": "hdn",
  "squamish": "squ",
  "salish": "str",
  "nootka": "nuk",
  "kwakiutl": "kwk",
  "ojibwa": "ojg",
  "delaware": "unm",
  "wichita": "wic",
  "dakota": "lkt",
  "seneca": "see",
  "oneida": "one",
  "yuchi": "yuc",
  "alabama": "akz",
  "tunica": "tun",
  "nez perce": "nez",
  "maidu": "nmu",
  "zoque": "zoc",
  "totonac": "top",
  "chontal": "chf",
  "tzeltal": "tzh",
  "tarascan": "tsz",
  "karok": "kyh",
  "pomo": "pom",
  "digueno": "dih",
  "zuni": "zun",
  "tiwa": "tix",
  "tewa": "tew",
  "luiseno": "lui",
  "hopi": "hop",
  "pima": "ood",
  "otomi": "ote",
  "mazahua": "maz",
  "mazateco": "maq",
  "mixtec": "mig",
  "cayapa": "cbi",
  "paez": "pbb",
  "itonama": "ito",
  "quechua": "quh",
  "aymara": "ayr",
  "araucanian": "arn",
  "island carib": "crb",
  "wapishana": "wap",
  "goajiro": "guc",
  "campa": "cni",
  "moxo": "ign",
  "amuesha": "ame",
  "jivaro": "jiv",
  "barasano": "bao",
  "ticuna": "tca",
  "carib": "car",
  "ocaina": "oca",
  "siriono": "srq",
  "guarani": "gug",
  "amahuaca": "amc",
  "chacobo": "cao",
  "apinaye": "apn",
  "shilha": "shi",
  "hausa": "hau",
  "angas": "anc",
  "margi": "mrt",
  "somali": "som",
  "awiya": "awn",
  "iraqw": "irk",
  "tigre": "tig",
  "amharic": "amh",
  "egyptian arabic": "arz",
  "moroccan arabic": "ary",
  "maltese": "mlt",
  "modern hebrew": "heb",
  "katcha": "xtc",
  "kpelle": "xpe",
  "wolof": "wol",
  "dagbani": "dag",
  "akan": "aka",
  "ga": "gaa",
  "ewe": "ewe",
  "igbo": "ibo",
  "beembe": "beq",
  "swahili": "swh",
  "luvale": "lue",
  "zulu": "zul",
  "gbeya": "gbp",
  "songhai": "ses",
  "kanuri": "knc",
  "logbara": "lgg",
  "mahas-fiyadikka": "fia",
  "luo": "luo",
  "maasai": "mas",
  "nama": "naq",
  "irish gaelic": "gle",
  "breton": "bre",
  "icelandic": "isl",
  "norwegian": "nor",
  "english": "eng",
  "german": "deu",
  "french": "fra",
  "portuguese": "por",
  "spanish": "spa",
  "rumanian": "ron",
  "russian": "rus",
  "bulgarian": "bul",
  "lithuanian": "lit",
  "albanian": "als",
  "modern greek": "ell",
  "armenian": "hye",
  "persian": "pes",
  "pashto": "pst",
  "kashimiri": "kas",
  "punjabi": "pan",
  "hindi-urdu": "hin",
  "bengali": "ben",
  "sinhalese": "sin",
  "basque": "eus",
  "finnish": "fin",
  "cheremis": "mhr",
  "komi": "kpv",
  "hungarian": "hun",
  "ostyak": "kca",
  "yurak": "yrk",
  "turkish": "tur",
  "azerbaijani": "azj",
  "kirghiz": "kir",
  "chuvash": "chv",
  "yakut": "sah",
  "khalkha": "khk",
  "even": "eve",
  "yukaghir": "ykg",
  "gilyak": "niv",
  "chukchi": "ckt",
  "ainu": "ain",
  "japanese": "jpn",
  "kotoko": "mpi",
  "achumawi": "acv",
  "arrernte": "aer",
  "amele": "aey",
  "angaatiha": "agm",
  "aghem": "agq",
  "aizi": "ahp",
  "ahtna": "aht",
  "akawaio": "ake",
  "qawasqar": "alc",
  "alladian": "ald",
  "hamer": "amf",
  "amo": "amo",
  "alamblak": "amp",
  "amuzgo": "amu",
  "andoke": "ano",
  "andamanese": "apq",
  "archi": "aqc",
  "arabela": "arl",
  "auca": "auc",
  "avar": "ava",
  "abipon": "axb",
  "bashkir": "bak",
  "bambara": "bam",
  "bariba": "bba",
  "bats": "bbl",
  "bobo-fing": "bbo",
  "bai": "bca",
  "bardi": "bcj",
  "kohumono": "bcs",
  "sama": "bdl",
  "bandjalang": "xjb",
  "beja": "bej",
  "bete": "bev",
  "bisa": "bib",
  "bakairi": "bkq",
  "bella coola": "blc",
  "muinane": "bmr",
  "birom": "bom",
  "bororo": "bor",
  "brao": "brb",
  "brahui": "brh",
  "bruu": "brv",
  "bodo": "brx",
  "burarra": "bvr",
  "baining": "byx",
  "bribri": "bzd",
  "caddo": "cad",
  "ashuslay": "cag",
  "nicobarese": "ncb",
  "nyah kur": "cbn",
  "cacua": "cbv",
  "fuzhou": "cdo",
  "highland chinantec": "chq",
  "cherokee": "chr",
  "upper chehalis": "cjh",
  "chuave": "cjv",
  "lai": "cnh",
  "cofan": "con",
  "konyagi": "cou",
  "hmong": "cqd",
  "tiddim chin": "ctd",
  "chatino": "ctp",
  "cubeo": "cub",
  "cayuvava": "cyb",
  "dangaleat": "daa",
  "dan": "daf",
  "daju": "daj",
  "dahalo": "dal",
  "dyirbal": "dbl",
  "diyari": "dif",
  "dinka": "din",
  "dani": "dni",
  "kam": "doc",
  "doayo": "dow",
  "rukai": "dru",
  "dagur": "dta",
  "dogon": "dts",
  "yolngu": "duj",
  "diola": "dyo",
  "efik": "efi",
  "ekari": "ekg",
  "yupik": "ess",
  "ejagham": "etu",
  "ewondo": "ewo",
  "eyak": "eya",
  "fasu": "faa",
  "fijian": "fij",
  "fe?fe?": "fmp",
  "iate": "fun",
  "fur": "fvr",
  "po-ai": "fwa",
  "garawa": "wrk",
  "gwari": "gbr",
  "gelao": "gqu",
  "nanai": "gld",
  "kullo": "dwr",
  "guahibo": "guh",
  "guambiano": "gum",
  "ache": "guq",
  "gugu-yalandyi": "gvn",
  "hixkaryana": "hix",
  "hadza": "hts",
  "huasteco": "hus",
  "huave": "huv",
  "iban": "iba",
  "kolokuma ijo": "ijc",
  "ik": "ikx",
  "irarutu": "irh",
  "iranxe": "irn",
  "isoko": "iso",
  "itelmen": "itl",
  "ivatan": "ivv",
  "iwam": "iwm",
  "jacaltec": "jac",
  "yanyuwa": "jao",
  "jebero": "jeb",
  "tol": "jic",
  "japreria": "jru",
  "jingpho": "kac",
  "camsa": "kbh",
  "koiari": "kbk",
  "kefa": "kbr",
  "dera": "kbv",
  "k'ekchi": "kek",
  "kera": "ker",
  "koya": "kff",
  "kaingang": "kgp",
  "lue": "khb",
  "kiowa": "kio",
  "southern kiwai": "kjd",
  "khmu?": "kjg",
  "acoma": "kjq",
  "kewa": "kjs",
  "teke": "kkw",
  "klamath": "kla",
  "klao": "klu",
  "kurdish": "ckb",
  "kanakuru": "kna",
  "konkani": "knn",
  "kpan": "kpk",
  "sre": "kpm",
  "koryak": "kpy",
  "sebei": "kpz",
  "kalkatungu": "ktg",
  "!xu": "ktz",
  "kunama": "kun",
  "cuna": "kvn",
  "kwaio": "kwd",
  "lelemi": "lef",
  "lame": "lme",
  "lushootseed": "lut",
  "maxakali": "mbl",
  "mambila": "mzk",
  "mbum": "mdd",
  "maba": "mde",
  "dizi": "mdx",
  "mba-ne": "mfc",
  "moghol": "mhj",
  "monguor": "mjg",
  "manchu": "mnc",
  "mor": "moq",
  "moro": "mor",
  "malakmalak": "mpb",
  "dadibi": "mps",
  "west makian": "mqs",
  "maranao": "mrw",
  "mixe": "mto",
  "mursi": "mur",
  "murinhpatha": "mwf",
  "kala lagaw ya": "mwp",
  "piraha": "myp",
  "mumuye": "mzm",
  "movima": "mzp",
  "southern nambiquara": "nab",
  "xiamen": "nan",
  "naxi": "nxq",
  "nahuatl": "ncj",
  "ndut": "ndv",
  "nepali": "npi",
  "newari": "new",
  "ngizim": "ngi",
  "noni": "nhu",
  "lua": "nie",
  "nganasan": "nio",
  "nimboran": "nir",
  "ao": "njo",
  "nera": "nrb",
  "lungchow": "nut",
  "nyimang": "nyi",
  "nyangi": "nyp",
  "ogbia": "ogb",
  "ormuri": "oru",
  "pacoh": "pac",
  "paya": "pay",
  "panare": "pbh",
  "pohnpeian": "pon",
  "parauk": "prk",
  "paiwan": "pwn",
  "phlong": "pww",
  "quileute": "qui",
  "resigaro": "rgr",
  "rotokas": "roo",
  "roro": "rro",
  "rutul": "rut",
  "sandawe": "sad",
  "sango": "sag",
  "senadi": "sef",
  "selkup": "sel",
  "shiriana": "shb",
  "shuswap": "shs",
  "shasta": "sht",
  "epena pedee": "sja",
  "sierra miwok": "skd",
  "saliba": "slc",
  "saami": "sma",
  "siona": "snn",
  "socotri": "sqt",
  "nambakaengo": "ntu",
  "suena": "sue",
  "savosavo": "svs",
  "sui": "swi",
  "tamang": "na",
  "huari": "tba",
  "tabi": "tbi",
  "tulu": "tcy",
  "tehuelche": "teh",
  "temne": "tem",
  "temein": "teq",
  "tetun": "tet",
  "tigak": "tgc",
  "tamasheq": "taq",
  "tiwi": "tiw",
  "tiruray": "tiy",
  "tlingit": "tli",
  "jomang": "tlo",
  "tama": "tma",
  "tacana": "tna",
  "lenakel": "tnl",
  "tampulma": "tpm",
  "tlapanec": "tpx",
  "trumai": "tpy",
  "taoripi": "tqo",
  "tonkawa": "tqw",
  "neo-aramaic": "trg",
  "tsimshian": "tsi",
  "tsou": "tsu",
  "tera": "ttr",
  "picuris": "twf",
  "tuva": "tyv",
  "ngarinjin": "ung",
  "uzbek": "uzn",
  "vanimo": "vam",
  "mbabaram": "vmb",
  "wappo": "wao",
  "warao": "wba",
  "wahgi": "wgi",
  "wintu": "wit",
  "wiyot": "wiy",
  "wantoat": "wnc",
  "usan": "wnu",
  "woisika": "woi",
  "waris": "wrs",
  "waray": "wrz",
  "berta": "wti",
  "ngiyambaa": "wyb",
  "kawaiisu": "xaw",
  "koma": "xom",
  "kadugli": "xtc",
  "yagua": "yad",
  "yaqui": "yaq",
  "yucuna": "ycn",
  "tarok": "yer",
  "yagaria": "ygr",
  "yidiny": "yii",
  "yana": "ynn",
  "yoruba": "yor",
  "yareba": "yrb",
  "yessan-mayo": "yss",
  "yucatec": "yua",
  "yulu": "yul",
  "yawa": "yva",
  "azande": "zne",
  "abidji": "abi",
  "adioukrou": "adj",
  "adja": "ajg",
  "agni sanvi": "mtb",
  "ahl": "ahl",
  "akse": "bss",
  "anuf": "cko",
  "arabe": "apd",
  "avokaya": "avu",
  "babungo": "bav",
  "bafut": "bfd",
  "baka": "bdh",
  "banda": "bfl",
  "bandi": "bza",
  "baoul": "bci",
  "basaa": "bas",
  "bassa": "bsq",
  "bassar": "bud",
  "bt": "btg",
  "bekwarra": "bkv",
  "b": "nhb",
  "bhele": "bhy",
  "biali": "beh",
  "bimoba": "bim",
  "boussa": "bqc",
  "bozo": "bzx",
  "bulu": "bum",
  "cerma": "cme",
  "chumburung": "ncu",
  "daba": "dbq",
  "dagaare": "dga",
  "dagara": "dgi",
  "dangme": "ada",
  "daza": "dzg",
  "dida": "dic",
  "dioula": "dyu",
  "ditammari": "tbz",
  "duala": "dua",
  "duruma": "dug",
  "ebira": "igb",
  "edo": "bin",
  "ezaa": "eza",
  "emai": "ema",
  "engenni": "enn",
  "fn": "fon",
  "fulfulde": "fuh",
  "fuliru": "flr",
  "gangam": "gng",
  "gbaya": "gya",
  "gn-mina": "gej",
  "godi": "god",
  "gonja": "gjn",
  "grebo": "gbo",
  "gue": "gde",
  "gulmancema": "gux",
  "hanga": "hag",
  "if": "ife",
  "igede": "ige",
  "ijo de l'est; eastern ijo": "ijs",
  "ikwo": "iqw",
  "izi": "izz",
  "jur md": "bex",
  "kabiy": "kbp",
  "kak": "kkj",
  "kambari": "bqx",
  "karaboro": "kza",
  "kara": "kzr",
  "kasem": "xsm",
  "kzime": "ozm",
  "kikuyu": "kik",
  "kisiei": "kqs",
  "kom": "bkm",
  "komo": "kmw",
  "konkomba": "xon",
  "kplwoo": "gkp",
  "kresh": "krs",
  "krio": "kri",
  "kroumen tpo": "ted",
  "kuria": "kuj",
  "kusal": "kus",
  "lama": "las",
  "lele": "llc",
  "lendu": "led",
  "lgmagooi": "lom",
  "lk": "lok",
  "ligbi": "lig",
  "limba": "lia",
  "limbum": "lmp",
  "lingala": "lin",
  "lokpa": "dop",
  "luganda": "lug",
  "lyl": "lee",
  "mampruli": "maw",
  "mande": "mlq",
  "manding": "emk",
  "mangbetu": "mdj",
  "maninka-kan": "mwk",
  "mnd": "muh",
  "mbembe": "nza",
  "mbo": "mbo",
  "mekaa": "mcp",
  "mende": "men",
  "metta": "mgo",
  "minyanka": "myk",
  "mo": "mzw",
  "mofu-gudur": "mif",
  "moore": "mos",
  "muan": "moa",
  "mundani": "mnf",
  "munukutuba": "mkw",
  "mwaghavul": "sur",
  "nafaanra": "nfr",
  "nawdm": "nmz",
  "nni": "nuv",
  "nmaa": "lem",
  "ngambai": "sba",
  "ngbaka": "nga",
  "ngbandi": "ngb",
  "ngyembn": "nnh",
  "niaboua": "nwb",
  "nso": "lns",
  "nugunu": "yas",
  "nupe": "nup",
  "pandikeri": "mhi",
  "podoko": "pbi",
  "pulaar": "fuc",
  "pular": "fuf",
  "rendille": "rel",
  "sabaot": "spy",
  "senoufo": "seq",
  "sereer": "srr",
  "sissala": "sld",
  "songhoy": "khq",
  "soninke": "snk",
  "soso": "sus",
  "tamajaq": "ttq",
  "tn": "lor",
  "teda": "tuq",
  "tem": "kdh",
  "tfin": "tfi",
  "tikar": "tik",
  "toposa": "toq",
  "toura": "neb",
  "toussian": "tsp",
  "vagala": "vag",
  "vute": "vut",
  "waama": "wwa",
  "wan": "wan",
  "wob": "wob",
  "yamba": "yam",
  "yambta": "yat",
  "yaour": "yre",
  "yemba": "ybb",
  "yom": "pil",
  "zarma": "dje",
  "zulgo": "gnd",
  "fwe": "fwe",
  "yeyi": "yey",
  "cavinena": "cav",
  "chamicuro": "ccc",
  "chechen": "che",
  "chepang": "cdm",
  "chinanteco": "cle",
  "tila, chiapas": "ctu",
  "chrau": "crw",
  "barbareo": "boi",
  "coeur d''alene'": "crd",
  "comanche": "com",
  "cupeno": "cup",
  "cuvok": "cuv",
  "denya": "anv",
  "dhangar": "kxl",
  "muhiang": "aoj",
  "usarufa": "usa",
  "korafe": "kpr",
  "binumarien": "bjr",
  "eggon": "ego",
  "ekpeye": "ekp",
  "endo": "enb",
  "esimbi": "ags",
  "fan": "fan",
  "furu": "fuu",
  "garadjari": "gbd",
  "gbari": "gby",
  "golin": "gvf",
  "guajajara": "gub",
  "gunwinggu": "gup",
  "haya": "hay",
  "huron": "wya",
  "huichol": "hch",
  "huaylas": "qwh",
  "huanca": "qxw",
  "louyi": "lyn",
  "ibani": "iby",
  "imonda": "imn",
  "ingush": "inh",
  "isaka": "ksi",
  "jalonke": "yal",
  "hill jarawa": "izr",
  "jarawara": "jaa",
  "jemez": "tow",
  "jili": "mgi",
  "kabyle": "kab",
  "kada": "gid",
  "kaiabi": "kyz",
  "kamasau": "kms",
  "kanoe": "kxo",
  "kensei nsei": "ndb",
  "kar": "xrb",
  "karipuna creole": "kmv",
  "kenyang": "ken",
  "chong": "cog",
  "kinyarwanda": "kin",
  "kirike": "okr",
  "kokota": "kkk",
  "kole": "kme",
  "konni": "kma",
  "kuay": "kdt",
  "kulung": "kle",
  "kuot": "kto",
  "kusunda": "kgg",
  "kuvi": "kxv",
  "kwaza": "xwa",
  "ladakhi": "lbj",
  "langi": "lag",
  "lao": "lao",
  "lavukaleve": "lvk",
  "bafo": "bwt",
  "lunda": "lun",
  "lucazi": "lch",
  "lukundu": "bdu",
  "macedonian": "mkd",
  "mada": "mda",
  "ma''di'": "grg",
  "manam": "mva",
  "mamenyan": "bce",
  "manange": "nmm",
  "ngemba": "nge",
  "mara": "mec",
  "maybrat": "ayz",
  "mbodomo; mbodm": "gmm",
  "medumba": "byv",
  "mingrelian": "xmf",
  "mmen": "bfm",
  "moken": "mwt",
  "moseten": "cas",
  "mpumpun": "mgg",
  "mungaka": "mhk",
  "mvumbo": "nmg",
  "mwotlap": "mlv",
  "namia": "nnm",
  "ndemli": "nml",
  "chiricahua apache": "apm",
  "yuma": "yum",
  "nankina": "nnk",
  "nandi": "niq",
  "khmu": "kig",
  "naki": "mff",
  "michoacan nahual": "ncl",
  "nagamese": "nag",
  "ngishe": "nsh",
  "ngalakan": "nig",
  "nganikurungkurr": "nam",
  "ngomba": "jgo",
  "ngombale": "nla",
  "northern khmer": "kxm",
  "northern paiute": "pao",
  "nubi": "kcn",
  "nuer": "nus",
  "nulibie": "ekm",
  "kinyamwezi": "nym",
  "nyeu": "nyl",
  "obolo": "ann",
  "mianmin": "mpt",
  "faiwol": "fai",
  "oku": "oku",
  "ossetian": "oss",
  "palauan": "pau",
  "orokaiva": "okv",
  "yil": "yll",
  "ningil": "niz",
  "dobu": "dob",
  "samo": "smq",
  "urii": "uvh",
  "boiken": "bzf",
  "pray": "prt",
  "mal": "mlf",
  "rama": "rma",
  "matbat": "xmt",
  "rundi": "run",
  "runyankore": "nyn",
  "marwari": "rwr",
  "samba leko": "ndi",
  "samo de toma": "sbd",
  "samre": "sxm",
  "sabane": "sae",
  "saanich": "str",
  "sasak": "sas",
  "savara": "svr",
  "popoluca de sayula": "pos",
  "secoya": "sey",
  "sedik": "trv",
  "seimat": "ssg",
  "semelai": "sza",
  "serrano": "ser",
  "shabo": "sbf",
  "shanenawa": "sha",
  "shimakonde": "kde",
  "shona": "sna",
  "shupamem": "bax",
  "siar-lak": "sjr",
  "siraiki": "skr",
  "shawnee": "sjw",
  "skou": "skv",
  "so": "thm",
  "south efate": "erk",
  "spokan": "spo",
  "sesotho": "sot",
  "satawalese": "stw",
  "sumo": "ulw",
  "hup": "jup",
  "san miguel chimalapa zoque": "zoh",
  "zapotec": "ztp",
  "yuki": "yuk",
  "yapese": "yap",
  "yurok": "yur",
  "yuracure": "yuz",
  "yukaghir (kolyma)": "yux",
  "wa": "wbm",
  "wambon": "wms",
  "washo": "was",
  "wayana": "way",
  "wogeo": "woc",
  "warihio": "var",
  "vai": "vai",
  "ukrainian": "ukr",
  "palula (phalura)": "phl",
  "east makian": "mky",
  "tapiete": "tpi",
  "baruga": "bjz",
  "tatuyo": "tav",
  "tagwana": "tgw",
  "mazanderani": "mzn",
  "pa-o, taungthu": "blk",
  "ternate": "tft",
  "toba (argentina)": "tob",
  "polish": "pol",
  "kalabari; kirike; kalabari-ijo": "ijn",
  "standard yiddish": "ydd",
  "dutch": "nld",
  "tamambo; malo": "mla",
  "gayo": "gay",
  "jamaican creole": "jam",
  "mambay; mambai": "mcs",
  "aragonese": "arg",
  "tilquiapan zapotec": "zts",
  "ibibio": "ibb",
  "tamil": "tam",
  "san bartolome zoogocho zapotec": "zpq",
  "baga koga; koba; barka": "bgo",
  "southern nuautl": "nxl",
  "selaru": "slu",
  "tsuvadi; avadi; abadi; evadi; kamberi; ibeto": "tvd",
  "hanga hundi; kwasengen; west wosera": "wos",
  "blang; plang; bulang; pulang; pula; kawa; k''ala; kontoi'": "blr",
  "tatana''; tatanaq; tatana'": "txx",
  "tibetan": "bod",
  "che; rukuba; kuche; bache; inchazi; sale": "ruk",
  "pagibete; apakabeti; apakibeti; apagibete;apagibeti; pagabete": "pae",
  "choctaw": "cho",
  "michif": "crg",
  "pilaga; pilag": "plg",
  "kurripako; baniwa; baniwa (icana)": "bwi",
  "karitiana; karitina": "ktn",
  "iupiaq; iupiat; inupiat; inupiaq": "esi",
  "tlacolula valley zapotec; western tlacolula zapotec; zapotec, san juan guelava": "zab",
  "tzotzil, chamula": "tzo",
  "sidaama; sidamo; sidamic": "sid",
  "bajau, west coast; land bajaw; west coast bajao": "bdr",
  "chimariko": "cid",
  "tepehua, huehuetla; tepehua de hidalgo; tepehua de huehuetla": "tee",
  "southern ute; ute; ute-southern paiute": "ute",
  "dupaningan agta; eastern cagayan agta; dupaninan agta": "duo",
  "tongan; tonga": "ton",
  "lake miwok; miwok (lake)": "lmw",
  "laz": "lzz",
  "juang": "jun",
  "adang": "adn",
  "ambele": "ael",
  "apurin": "apu",
  "acehnese": "ace",
  "antiguan creole": "aig",
  "aklan": "akl",
  "ika": "arh",
  "karo": "arr",
  "lebanese arabic": "ayl",
  "remo": "bfw",
  "bikele": "biw",
  "blackfoot": "bla",
  "biloxi": "bll",
  "belizean creole": "bzj",
  "koasati": "cku",
  "comox": "coo",
  "sochiapan chinantec": "cso",
  "dimili": "diq",
  "etsako": "ets",
  "frisian": "fry",
  "gojri; gujari; gujar": "gju",
  "wanano": "gvc",
  "kihungan": "hum",
  "chilliwak halkomelem": "hur",
  "ilocano": "ilo",
  "kadiweu": "kbc",
  "kuteb": "kub",
  "awa pit": "kwi",
  "lisu": "lis",
  "loniu": "los",
  "molalla": "mbe",
  "matses": "mcf",
  "manipuri": "mni",
  "mandingo": "mnk",
  "mocovi": "moc",
  "western mam; tacanec": "mam",
  "munduruku": "myu",
  "nishgha": "ncg",
  "low german": "nds",
  "northern pame": "pmq",
  "panamint": "par",
  "nigerian pidgin": "pcm",
  "northern pomo": "pej",
  "texistepec popoluca": "poq",
  "catalan": "cat",
  "croatian": "hrv",
  "czech": "ces",
  "galician": "glg",
  "mono": "mru",
  "indonesian": "ind",
  "italian": "ita",
  "salasaca quichua": "qxl",
  "seri": "sei",
  "sindhi": "snd",
  "slovene": "slv",
  "swedish": "swe",
  "tukang besi": "khc",
  "yine": "pib",
  "quiche": "quc",
  "huallaga (huanuco) quechua": "qvh",
  "sipakapense maya": "qum",
  "chimborazo quichua": "qug",
  "tepehua": "tpt",
  "abulas": "abt",
  "abau": "aau",
  "agaw": "ahg",
  "akha": "ahk",
  "alyawarra": "aly",
  "amanab": "amn",
  "anywa": "anu",
  "arandai": "jbj",
  "arapesh": "aon",
  "tanacross": "tcb",
  "au": "avt",
  "tinputz": "tpz",
  "petats": "pex",
  "patep": "ptp",
  "kela": "kcl",
  "sursurunga": "sgz",
  "awara": "awx",
  "awing": "azo",
  "awtuw": "kmn",
  "baba": "bbw",
  "babanki": "bbk",
  "bakoko": "bkh",
  "bali-kumbat": "muo",
  "bamunka": "bvm",
  "bangolan": "bgj",
  "banoo": "bnm",
  "bariai": "bch",
  "befang": "bby",
  "ida''an'": "dbj",
  "bemba": "bem",
  "berbice dutch": "brc",
  "betta kurumba": "xub",
  "biak": "bhw",
  "bilinara": "nbj",
  "binandere": "bhg",
  "bobo": "bwq",
  "bole": "bol",
  "bongo": "bot",
  "boro": "bwo",
  "brokskat": "bkk",
  "baga sitem": "bsp",
  "bubia": "bbx",
  "bukusu": "bxk",
  "subiya": "sbs",
  "totela": "ttl",
  "bambalang; ciramb": "bmo",
  "north marquesan": "mrq",
  "ge; ong; onge": "oon",
  "oluta popoluca; olutec": "plo",
  "jiarong": "jya",
  "suri": "suq",
  "bilua": "blb",
  "hoava": "hoa",
  "filipino": "fil",
  "ngad''a; ngadha'": "nxg",
  "muna": "mnb",
  "ke''o; keo'": "xxk",
  "sakirabi; mekens": "skf",
  "torwali": "trw",
  "thulung; thulung rai": "tdh",
  "tshangla": "tsj",
  "colorado; tsafiki": "cof",
  "tzutujil": "tzj",
  "kinnauri; kanauri": "kfk",
  "mewati": "wtm",
  "aneityum; anejom": "aty",
  "zaiwa": "atb",
  "chickasaw": "cic",
  "friulian": "fur",
  "jicarilla apache": "apj",
  "ega": "ega",
  "arrarnte": "are",
  "sanuma; sanuma": "xsu",
  "wari; wari''; wari; oro nao'": "pav",
  "crow": "cro",
  "anyi sanvi": "any",
  "babole": "bvx",
  "bana": "bcw",
  "aja": "aja",
  "bila": "bip",
  "busa": "bqp",
  "fulfulde (nga)": "fuv",
  "herero": "her",
  "kpa": "ksf",
  "lega-shabunda": "lea",
  "myene": "mye",
  "nen": "tvu",
  "matuumbi": "mgw",
  "umbundu": "umb",
  "ndonga": "ndo",
  "mbukushu": "mhw",
  "diriku": "diu",
  "kwangari": "kwn",
  "ikalanga": "kck",
  "mongo-nkundu": "lol",
  "longto": "wok",
  "xwela": "xwe",
  "western xwla": "xwl",
  "kotafon": "kqk",
  "gbesi": "gbs",
  "machame": "jmc",
  "mbe": "mtk",
  "ngwe": "nwe",
  "jowulu": "jow",
  "yala": "yba",
  "cilungu": "mgr",
  "kete": "kcv",
  "kwezo": "kws",
  "madi": "snm",
  "moru": "mgd",
  "logo": "log",
  "afitti": "aft",
  "avatime": "avn",
  "abua": "abn",
  "dghwede": "dgh",
  "eloyi": "afo",
  "gechode": "acd",
  "genyanga": "ayg",
  "kilba": "hbb",
  "kofyar": "kwl",
  "krache": "kye",
  "krim": "krm",
  "banda, west central": "bbp",
  "dinka, south central": "dib",
  "foodo": "fod",
  "joola huluf": "csk",
  "jumjum": "jum",
  "burun": "bdi",
  "lulubo": "lul",
  "maay": "ymm",
  "mabaan": "mfz",
  "nizaa": "sgi",
  "copi": "cce",
  "xhosa": "xho",
  "siwu": "akp",
  "sherbro": "bun",
  "mmani": "buy",
  "hill guang": "cpn",
  "ndut-falor": "fap",
  "frafra": "gur",
  "likpe": "lip",
  "shanjo": "toi",
  "pajade": "pbp",
  "sele": "snw",
  "tiv": "tiv",
  "blin": "byn",
  "xamtanga": "xan",
  "lika": "lik",
  "yanzi": "yns",
  "kibudu": "buu",
  "iikile": "khy",
  "lengola": "lej",
  "kaliko": "kbo",
  "wongo": "won",
  "mwali": "wlc",
  "afar": "aar",
  "mundang": "mua",
  "tupuri": "tui",
  "kuo": "xuo",
  "kare": "kbn",
  "galke": "gke",
  "northern mao": "myf",
  "tigrinya": "tir",
  "karimojong": "kdj",
  "gwandara (karshi)": "gwn",
  "avikam": "avi",
  "shilluk": "shk",
  "san": "hgm",
  "pero": "pip",
  "galla": "gax",
  "hadiyya": "hdy",
  "welamo": "wal",
  "nyanga": "njx",
  "otuho": "lot",
  "orusyan": "myx",
  "higi": "hig",
  "manya": "mzj",
  "syan": "say",
  "nzbi": "nzb",
  "tadaksahak": "dsq",
  "kambaata": "ktb",
  "otoro": "otr",
  "tira": "tic",
  "nyam": "nmi",
  "kirya-konzl": "fli",
  "mawa": "mcw",
  "!xoo": "nmn",
  "koalib": "kib",
  "kagulu": "kki",
  "oko": "oks",
  "!xun": "knw",
  "banjun": "bbj",
  "defaka": "afn",
  "tee": "tkq",
  "kipsigis": "sgc",
  "pangwa": "pbr",
  "holoholo": "hoo",
  "buli": "bwu",
  "balante": "bjt",
  "kinyambo": "now",
  "pokot": "pko",
  "afrikaans": "afr",
  "argobba": "agj",
  "harari": "har",
  "nzema": "nzi",
  "ahanta": "aha",
  "besleri": "hna",
  "buwal": "bhs",
  "hide": "xed",
  "lamang": "hia",
  "ikwere": "ikw",
  "lagwan": "kot",
  "mbuko": "mqb",
  "moloko": "mlw",
  "muyang": "muy",
  "kemezung": "dmo",
  "nateni": "ntm",
  "silt'i": "stv",
  "weh": "weh",
  "tulishi": "tey",
  "keiga": "kec",
  "krongo": "kgo",
  "kanga (kanga)": "kcp",
  "morokodo": "mgc",
  "aringa": "luc",
  "these": "keg",
  "lumun": "lmd",
  "asharon": "acz",
  "tocco": "taz",
  "thakik": "dec",
  "didinga": "did",
  "luwo": "lwo",
  "acholi": "ach",
  "belanda boor": "bxb",
  "belanda viri": "bvi",
  "ndogo": "ndz",
  "bade": "bde",
  "pichi": "fpe",
  "jita": "jit",
  "dime": "dim",
  "lutsootso": "lto",
  "jamsay, dogon": "djm",
  "kikamba": "kam",
  "lango": "lno",
  "olukisa": "lks",
  "nyole": "nuj",
  "kimwani": "wmw",
  "shekgalagari": "xkv",
  "tigemaxo bozo": "boz",
  "alaaba": "alw",
  "degema": "deg",
  "principense": "pre",
  "nkonya": "nko",
  "soddo": "gru",
  "goggot": "gru",
  "masqan": "mvz",
  "muher": "sgw",
  "ezha": "sgw",
  "chaha": "sgw",
  "gumer": "sgw",
  "ennemor": "ior",
  "dzuungoo": "dnn",
  "bagirmi": "bmi",
  "ngiti": "niy",
  "chindali": "ndh",
  "me'en": "mym",
  "ongamo": "nsg",
  "mbay": "myb",
  "gumuz": "guk",
  "soo": "teu",
  "gimira": "bcq",
  "yemsa": "jnj",
  "zayse": "zay",
  "gamo": "gmv",
  "koorete": "kqy",
  "aari": "aiw",
  "twampa": "udu",
  "opo": "lgn",
  "kwama": "kmq",
  "mayogo": "mdm",
  "lusaamia": "lsm",
  "nouni": "nnw",
  "ndebele": "nde",
  "saxwe, gbe": "sxw",
  "laarim": "loh",
  "bijogo": "bjg",
  "dompo": "doy",
  "heiban": "hbn",
  "koyaga": "kga",
  "cwaya": "shw",
  "tiba": "ttb",
  "kwanyama": "kua",
  "mbalanhu": "lnb",
  "kwambi": "kwm",
  "ngandjera": "nne",
  "beria": "zag",
  "zway": "zwa",
  "leke": "zmx",
  "bena": "bez",
  "kakabe": "kke",
  "mano": "mev",
  "kyanga": "tye",
  "shanga": "sho",
  "abure": "abu",
  "bankon": "abb",
  "efutu": "afu",
  "arbore": "arv",
  "aizi, tiagba": "ahi",
  "tinr": "ahs",
  "shindazidja": "zdj",
  "akpes": "ibe",
  "iten": "etx",
  "west kainji": "gel",
  "idu": "idu",
  "rigwe": "iri",
  "jere": "jer",
  "leggbo": "agb",
  "logba": "lgq",
  "glavda": "glw",
  "ahaan": "ahn",
  "uwu": "aye",
  "ronga": "rng",
  "comorian, ndzwani": "wni",
  "birifor": "biv",
  "kwatay": "cwt",
  "attie": "ati",
  "angolar": "aoa",
  "oromo, eastern": "hae",
  "kriyol": "pov",
  "bakaka (mwaneka)": "bqz",
  "bassossi": "bsi",
  "liberian english": "lir",
  "gban": "ggu",
  "eton": "eto",
  "reunionnais": "rcf",
  "masalit": "mls",
  "saotomense": "cri",
  "tangale": "tan",
  "sukuma": "suk",
  "mauritian creole": "mfe",
  "kituba": "ktu",
  "akasilimi": "aks",
  "tuki": "bag",
  "bum": "bmv",
  "gavar": "gou",
  "kwanja": "knp",
  "mere": "meq",
  "mandara": "mfi",
  "chonyi": "coh",
  "digo": "dig",
  "giryama": "nyf",
  "kambe": "nyf",
  "kauma": "nyf",
  "vame": "mlr",
  "numala": "mmu",
  "nchane": "ncr",
  "mfumte": "nfu",
  "njem": "njy",
  "bwamut": "box",
  "kwami": "ktf",
  "gouro": "goa",
  "cape verde creole": "kea",
  "kulango": "nku",
  "ts'amakko": "tsb",
  "tamazight berber": "tzm",
  "siwi": "siz",
  "ndamba": "ndj",
  "barein (jalkiya)": "bva",
  "mungbam": "mij",
  "mundabli": "boe",
  "ajumbu": "muc",
  "koshin": "kid",
  "fang": "fak",
  "kuranko": "knk",
  "gisiga": "gis",
  "moghamo": "mgo",
  "mokpwe": "bri",
  "siamou": "sif",
  "orma": "orc",
  "pinyin": "pny",
  "pana": "pnz",
  "thok reel": "atu",
  "ouldeme": "udl",
  "balese": "les",
  "kigweno": "gwe",
  "sisumbwa": "suw",
  "luzinza": "zin",
  "kimeru": "mer",
  "kikahe": "hka",
  "kihangaza": "han",
  "kimochi": "old",
  "kisimbiti": "ssc",
  "eciruuri": "kya",
  "wawa": "www",
  "tounia": "tug",
  "nchufie": "bfj",
  "burji": "bji",
  "anii": "blo",
  "fipa": "fip",
  "nawuri": "naw",
  "anfillo": "myo",
  "bokala-nkole": "nto",
  "talasa": "tbr",
  "iyive": "uiv",
  "karo batak": "btx",
  "southern sama": "ssb",
  "kimaragang": "kqr",
  "belait": "beg",
  "phan rang cham (eastern cham)": "cjm",
  "moklen": "mkm",
  "nias": "nia",
  "buol": "blf",
  "makassar": "mak",
  "mori bawah": "xmz",
  "kambera": "xbr",
  "leti": "lti",
  "ambon malay": "abs",
  "banda malay": "bpq",
  "manado malay": "xmm",
  "kupang malay": "mkn",
  "larantuka malay": "lrt",
  "north maluku malay": "max",
  "madurese": "mad",
  "cebuano": "ceb",
  "balinese": "ban",
  "bugis": "bug",
  "bikol (bicolano)": "bcl",
  "hiligaynon": "hil",
  "kapampangan": "pam",
  "minangkabau": "min",
  "pagasinan": "pag",
  "tengger": "tes",
  "abujmaria": "mrr",
  "angami": "njm",
  "apatani": "apt",
  "assamese": "asm",
  "awadhi": "awa",
  "badaga": "bfq",
  "balti": "bft",
  "banjara": "lmn",
  "bhili": "bhb",
  "bundeli": "bns",
  "chandangs and byangs": "cdn",
  "chokri": "nri",
  "darmiya": "drd",
  "didayi": "gaq",
  "gade-lohar": "gda",
  "gallong": "adl",
  "gujarati": "guj",
  "gutob": "gbj",
  "halbi": "hlb",
  "ho": "hoc",
  "irula": "iru",
  "jaunsari": "jns",
  "kangri": "xnr",
  "kannada": "kan",
  "kanigke:rgotti": "saz",
  "karbi (mikir)": "mjw",
  "kattunaika": "xuj",
  "khezha": "nkh",
  "kodagu": "kfa",
  "kolami": "kfb",
  "konda or kubi": "kfc",
  "konekar gadaba": "gau",
  "koraga": "kfd",
  "korku": "kfq",
  "kui": "kxu",
  "kumauni": "kfy",
  "lepca": "lep",
  "lotha": "njh",
  "lushai": "lus",
  "maithili": "mai",
  "malayalam": "mal",
  "malto": "mjt",
  "mao-naga": "nbi",
  "marathi": "mar",
  "mishmi": "mxj",
  "mising": "mrg",
  "moyon": "nmo",
  "naiki": "nit",
  "ollari": "gdb",
  "oriya": "ory",
  "paite": "pck",
  "parji": "pci",
  "pattani": "lae",
  "pengo": "peg",
  "sanskrit": "san",
  "santali": "sat",
  "sema": "nsm",
  "shina": "scl",
  "sora": "srb",
  "tangkul naga": "nmf",
  "tangsa": "nst",
  "thaadou": "tcz",
  "toda": "tcx",
  "tripuri": "trp",
  "urali": "url",
  "urdu": "urd",
  "vaagri boli": "vaa",
  "yerava": "yea",
  "yerukala": "yeu",
  "achagua": "aca",
  "lokono": "arw",
  "ashninka": "cpb",
  "bar": "mot",
  "cabiyar": "cbb",
  "caquinte": "cot",
  "curripaco": "kpc",
  "enawen-naw": "unk",
  "iapari": "inp",
  "kinikinao": "gqn",
  "manchinere": "mpd",
  "matsigenka": "mcb",
  "mehinku": "mmh",
  "nanti": "cox",
  "nomatsigenga": "not",
  "palikr": "plu",
  "paraujano": "pbg",
  "pares": "pab",
  "piapoco": "pio",
  "tariana": "tae",
  "terna": "ter",
  "warekena": "gae",
  "waur": "wau",
  "xirina": "xir",
  "yavitero": "yvt",
  "yawalapit": "yaw",
  "baure": "brg",
  "den": "dny",
  "kulina": "cul",
  "paumar": "pad",
  "suruah": "swx",
  "bora": "boa",
  "miraa": "boa",
  "shawi": "cbt",
  "akurio": "ako",
  "apala": "apy",
  "arra, par": "aap",
  "carijona": "cbd",
  "ikpeng": "txi",
  "kaxuina": "kbb",
  "kuikro-kalaplo": "kui",
  "macushi": "mbc",
  "mapoyo": "mcg",
  "yekwana": "mch",
  "pemon": "aoc",
  "pmono": "pev",
  "tri": "tri",
  "waimiri-atroar": "atr",
  "waiwai": "waw",
  "yabarana": "yar",
  "oro win": "orw",
  "muisca": "chb",
  "chimila": "cbg",
  "kogi": "kog",
  "damana": "mbp",
  "tunebo": "tuf",
  "woun meu": "noa",
  "ember-baud": "bdc",
  "ember-cato": "cto",
  "ember-cham": "cmi",
  "northern ember": "emp",
  "gnn yajich": "pue",
  "chon": "ona",
  "kokama-kokamilla": "cod",
  "cuiba": "cui",
  "guayabero": "guo",
  "macagun": "mbn",
  "amarakaeri": "amr",
  "choln": "cht",
  "awa": "ash",
  "candoshi-shapra": "cbu",
  "leco": "lec",
  "mochica": "omc",
  "muniche": "myr",
  "puinave": "pui",
  "taushiro": "trr",
  "tinigua": "tit",
  "urarina": "ura",
  "vilela": "vil",
  "yahgan": "yag",
  "achuar-shiwiar": "acu",
  "aguaruna": "agr",
  "huambisa": "hub",
  "nukak": "mbr",
  "katukna": "knt",
  "arikap": "ark",
  "canela": "ram",
  "bsro": "cax",
  "gavio do par": "gvp",
  "guat": "gta",
  "jabut": "jbt",
  "karaj": "kpj",
  "mebengokre": "txu",
  "krah": "xra",
  "krenak": "kqq",
  "krinkati-timbira": "xri",
  "ofay": "opy",
  "panar": "kre",
  "puri": "prr",
  "rikbaktsa": "rkb",
  "suy": "suy",
  "umotna": "umo",
  "xavnte": "xav",
  "xernte": "xer",
  "xokleng": "xok",
  "kaingng, so paulo": "zkp",
  "chorote": "crq",
  "maka": "mca",
  "wich": "mtp",
  "callawaya": "caw",
  "dw": "kwa",
  "nadb": "mbj",
  "yuhup": "yab",
  "kithaulhu": "nab",
  "latunde": "ltn",
  "mamaind": "wmd",
  "arara do acre": "mcd",
  "capanahua": "kaq",
  "cashibo-cacataibo": "cbr",
  "kashinawa": "cbs",
  "kaxarar": "ktx",
  "korubo": "xor",
  "mats": "mpq",
  "nukini": "nuc",
  "panobo": "pno",
  "poyanwa": "pyn",
  "saynawa": "sya",
  "shipibo": "shp",
  "yaminawa": "yaa",
  "yora": "mts",
  "yameo": "yme",
  "ancash quechua": "qwa",
  "cajamarca quechua": "qvc",
  "chachapoyas quechua": "quk",
  "cuzco-collao quechua": "quz",
  "ferreafe quechua": "quf",
  "imbabura quichua": "qvi",
  "inga": "inj",
  "north junn quechua": "qvn",
  "ayacucho quechua": "quy",
  "bolivian quechua": "qul",
  "huallaga hunuco quechua": "qub",
  "huaylas-conchucos quechua": "qxn",
  "san martin quechua": "qvs",
  "santiago del estero quechua": "qus",
  "napo quichua": "qvo",
  "tena quechua": "quw",
  "piaroa": "pid",
  "araona": "aro",
  "ese ejja": "ese",
  "reyesano": "rey",
  "barasana-eduria": "bsn",
  "desano": "des",
  "karapan": "cbc",
  "koreguaje": "coe",
  "macuna": "myy",
  "mhki": "ore",
  "piratapuyo": "pir",
  "siriano": "sri",
  "tanimuca-retuar": "tnc",
  "tucano": "tuo",
  "tuyuca": "tue",
  "yurut": "yui",
  "akunts": "aqz",
  "amundava": "adw",
  "apiak": "api",
  "arawet": "awt",
  "asurini do xing": "asn",
  "asurin do tocantins": "asu",
  "av-canoeiro": "avv",
  "awet": "awe",
  "chiriguano": "gui",
  "emerillon": "eme",
  "gavio do jiparan": "gvo",
  "guaj": "gvj",
  "mby": "gun",
  "guarayu": "gyr",
  "jma": "jua",
  "jurna": "jur",
  "kaapor": "urb",
  "kaiw": "kgk",
  "kamayur": "kay",
  "kuruya": "kyr",
  "makurp": "mpu",
  "nheengat": "yrl",
  "omagua": "omg",
  "pai tavytera": "pta",
  "parakan": "pak",
  "sater-maw": "mav",
  "suru": "sru",
  "tapiet": "tpj",
  "tapirap": "taf",
  "temb": "tqb",
  "tenharim": "pah",
  "tupar": "tpr",
  "tupinamb": "tpn",
  "uru-eu-wau-wau": "urz",
  "wayampi": "oym",
  "xet": "xet",
  "xipaya": "xiy",
  "zo'": "pto",
  "yuqui": "yuq",
  "arra do mato grosso": "axg",
  "hoti": "yau",
  "karir-xoc": "kzw",
  "kunza": "kuz",
  "pum": "yae",
  "chipaya": "cap",
  "uru": "ure",
  "huitoto, minica": "hto",
  "huitoto, murui": "huu",
  "nonuya": "noj",
  "yanommi": "wca",
  "yanomam": "guu",
  "chamacoco": "ceg",
  "ayoreo": "ayo",
  "andoa": "anb",
  "iquito": "iqu",
  "zparo": "zro",
  "nhandeva": "nhd",
  "pisamira": "na",
  "pacahuara": "pcp",
  "yukpa": "yup",
  "trinitario": "trn",
  "arabic": "arb",
  "danish": "dan",
  "luanyjang dinka": "dik",
  "estonian": "ekk",
  "swiss german": "gsw",
  "judeo-spanish": "lad",
  "lizu": "na",
  "luxembourgish": "ltz",
  "mah meri": "mhe",
  "mavea": "mkv",
  "central sama": "sml",
  "slovak": "slk",
  "tausug (suluk)": "tsg",
  "itunyoso trique": "trq",
  "isthmus (juchitn) zapotec": "zai",
  "bukharan tajik": "bhh",
  "kumzari": "zum",
  "cocos malay": "coa",
  "mennonite plautdietsch": "pdt",
  "kedayan": "kxd",
  "pitjantjatjara": "pjt",
  "southeastern pashayi": "psi",
  "greek thrace xoraxane romane": "rmy",
  "xumi": "sxg",
  "upper saxon": "sxu",
  "pite saami": "sje",
  "northern saami": "sme",
  "belhare": "byw",
  "hunzib": "huz",
  "evenki": "evn",
  "hmong njua": "hnj",
  "udmurt": "udm",
  "eastern yugur": "yuy",
  "moksha": "mdf",
  "rjbanshi": "rjs",
  "bakhtiari": "bqi",
  "dolgan": "dlg",
  "darkhat": "drh",
  "south azerbaijani": "azb",
  "kildin saami": "sjd",
  "glo tibetan": "loy",
  "tod tibetan": "sbu",
  "tajik": "tgk",
  "yongning na": "nru",
  "beserman": "udm",
  "ishkashimi": "isk",
  "hill mari": "mrj",
  "mirandese": "mwl",
  "modern aramaic": "na",
  "juhuri": "jdt",
  "munji": "mnj",
  "naukan yupik": "ynk",
  "thakali": "ths",
  "puxi": "jih",
  "bhujel": "byh",
  "kangjia": "kxs",
  "vallader romansh": "roh",
  "solu sherpa": "xsr",
  "lezgian": "lez",
  "humla bhotia": "hut",
  "northeastern thai": "tts",
  "dhivehi": "div",
  "buriat": "bxr",
  "karakalpak": "kaa",
  "yousafzai pashto": "pbu",
  "ligurian": "lij",
  "votic": "vot",
  "rgyalthang tibetan": "khg",
  "tsez": "ddo",
  "wymysorys": "wym",
  "gagauz": "gag",
  "northwestern pashto": "pbu",
  "soutern tai": "sou",
  "kunigami": "xug",
  "rusyn": "rue",
  "gurung": "gvr",
  "western balochi": "bgn",
  "baima": "bqh",
  "adyghe": "ady",
  "northern cuona": "dka",
  "kumyk": "kum",
  "chantyal": "chx",
  "bhojpuri": "bho",
  "gheg albanian": "aln",
  "rawang": "raw",
  "saek": "skb",
  "gorum": "pcj",
  "shan": "shn",
  "spiti tibetan": "spt",
  "northern altai": "atv",
  "faroese": "fao",
  "southern cuona": "dzl",
  "zuberoan basque": "eus",
  "yodzyak komi": "kom",
  "ksingmul": "puo",
  "dolakha newar": "na",
  "yolmo": "scp",
  "svan": "sva",
  "kyirong tibetan": "kgy",
  "dzongkha": "dzo",
  "hayu": "vay",
  "karaim": "kdr",
  "varli": "vav",
  "welsh": "cym",
  "japhug": "jya",
  "alutor": "alr",
  "denjongka": "sip",
  "yaghnobi": "yai",
  "zhongu tibetan": "na",
  "nyaw": "nyw",
  "northern qiang": "cng",
  "khakas": "kjh",
  "eastern khanty": "na",
  "arbresh albanian": "aae",
  "kurtoep": "xkz",
  "tukita": "kpt",
  "vro": "vro",
  "karelian": "krl",
  "livonian": "liv",
  "forest nenets": "na",
  "miyako": "mvi",
  "magahi": "mag",
  "purki": "prx",
  "kamassian": "xas",
  "dhimal": "dhi",
  "mongolian": "mon",
  "andi": "ani",
  "forest enets": "enf",
  "tay daeng": "tyr",
  "elfdalian": "ovd",
  "nyinpa cone": "cde",
  "northern mansi": "mns",
  "dongxiang": "sce",
  "occitan": "oci",
  "konda": "knd",
  "nuosu": "iii",
  "veps": "vep",
  "myeik burmese": "tvn",
  "latvian": "lvs",
  "ter saami": "sjt",
  "eastern hill balochi": "bgp",
  "serbian": "srp",
  "labrang tibetan": "scu",
  "scots": "sco",
  "mehri": "gdq",
  "wakhi": "wbl",
  "asturian": "ast",
  "phu tai": "pht",
  "northern thai": "nod",
  "salar": "slr",
  "walungge": "ola",
  "domari": "rmt",
  "khalong tibetan": "adx",
  "khalkhal": "tks",
  "muria gondi": "mut",
  "tofa": "kim",
  "upper sorbian": "hsb",
  "southern balochi": "bcc",
  "campidanese sardinian": "sro",
  "achang": "acn",
  "ahi": "yix",
  "temiar": "tea",
  "godoberi": "gdo",
  "skolt saami": "sms",
  "jah-hut": "jah",
  "udihe": "ude",
  "tai nuea": "tdd",
  "komi-permyak": "koi",
  "tay yo": "tyj",
  "southern pumi": "pmj",
  "southwestern pashto": "pbt",
  "baoan": "peh",
  "waneci": "wne",
  "digor ossetic": "oss",
  "latgalian": "ltg",
  "turkmen": "tuk",
  "jrriais": "nrf",
  "kalmyk": "xal",
  "scottish gaelic": "gla",
  "lower sorbian": "dsb",
  "najdi arabic": "ars",
  "tatar": "tat",
  "uyghur": "uig",
  "erzya": "myv",
  "nar-phu": "npa",
  "jibbali": "shv",
  "pnar": "pbv",
  "bunuba": "bck",
  "gooniyandi": "gni",
  "matngele": "zml",
  "murrinh-patha": "mwf",
  "patjtjamalh": "wdj",
  "marramaninyshi": "zmm",
  "marringarr": "zmt",
  "marrithiyel": "mfr",
  "marti ke": "zmg",
  "emmi": "amy",
  "larrakia": "lrg",
  "limilngan": "lmc",
  "umbugarla": "umr",
  "waanyi": "wny",
  "erre": "err",
  "mengerrdji": "zme",
  "urningangg": "urc",
  "anindilyakwa": "aoi",
  "dalabon": "ngk",
  "gaagudju": "gbu",
  "ngandi": "nid",
  "gun-dedjnjenghmi": "gup",
  "kune": "gup",
  "kuninjku": "gup",
  "kunwinjku": "gup",
  "mayali": "gup",
  "jawoyn": "djn",
  "rembarrnga": "rmb",
  "amurdak": "amg",
  "marrgu": "mhg",
  "wurrugu": "wur",
  "garig": "ilg",
  "ilgar": "ilg",
  "iwaidja": "ibd",
  "miriwoong": "mep",
  "kija": "gia",
  "kungarakany": "ggk",
  "ndjebbana": "djj",
  "gurr-goni": "gge",
  "nakara": "nck",
  "warndarrang": "wnd",
  "mangarrayi": "mpc",
  "jaminjung": "djd",
  "ngaliwurru": "djd",
  "nungali": "nug",
  "ngarnka": "nji",
  "jingulu": "jig",
  "binbinka": "wmb",
  "gudanji": "wmb",
  "wambaya": "wmb",
  "minkin": "na",
  "ngumbarl": "na",
  "nyikina": "nyh",
  "warrwa": "wwr",
  "jukun": "dyd",
  "yawuru": "ywr",
  "nimanburu": "nmp",
  "jabirr-jabirr": "dyb",
  "jawi": "djw",
  "nyulnyul": "nyv",
  "eastern anmatyerre": "amx",
  "western anmatyerre": "amx",
  "antekerrepenhe": "adg",
  "central arrernte": "aer",
  "ayerrerenge": "axe",
  "lower southern aranda": "axl",
  "kaytetye": "gbb",
  "bundjalung": "xjb",
  "gidabal": "gih",
  "guwar": "na",
  "minjungbal": "xjb",
  "waalubal": "bdy",
  "buwandik": "xbg",
  "warrnambool": "na",
  "gamilaraay": "kld",
  "muruwari": "zmu",
  "wayilwan": "wyb",
  "wiradjuri": "wrh",
  "wiriyaraay": "kld",
  "yuwaalaraay": "kld",
  "yuwaliyaay": "kld",
  "dhudhuroa": "na",
  "jandai": "jan",
  "turubul": "yxg",
  "warrgamay": "wgy",
  "baanbay": "kgs",
  "yaygir": "xya",
  "guwa": "xgw",
  "yanda": "yda",
  "yalarnnga": "ylr",
  "payungu": "bxj",
  "purduna": "bxn",
  "thalanyji": "dhl",
  "jiwarli": "dze",
  "tharrkari": "dhr",
  "thiin": "iin",
  "warriyangga": "wri",
  "mithaka": "na",
  "thirarri": "dit",
  "karangura": "nmv",
  "ngamini": "nmv",
  "pirlatapa": "bxi",
  "yandruwandha": "ynd",
  "nhirrpi": "hrp",
  "yawarrawarrka": "yww",
  "punthamara": "xpt",
  "kungardutji": "xwk",
  "arabana": "ard",
  "wangkangurru": "wgg",
  "pitta pitta": "pit",
  "wangkayutyuru": "wnm",
  "kungkari": "lku",
  "pirriya": "xpa",
  "garlali": "gll",
  "badimaya": "bia",
  "malkana": "vml",
  "nhanda": "nha",
  "watjarri": "wbv",
  "yingkarta": "yia",
  "kolakngat": "na",
  "daungwurrung": "dgw",
  "boonwurrung": "wyi",
  "wathawurrung": "wth",
  "yari-yari": "na",
  "ladji-ladji": "llj",
  "madhi-madhi": "dmd",
  "wathi wathi": "xwd",
  "east djadjawurung": "na",
  "jardwadjali": "na",
  "nari nari": "rnr",
  "djabwurung": "tjw",
  "wemba wemba": "xww",
  "wotjobaluk": "xwt",
  "bidhawal": "ihw",
  "muk-thang": "unn",
  "keramin": "na",
  "ngayawang": "na",
  "ngintait": "na",
  "yaraldi": "nay",
  "yitha yitha": "xth",
  "bidyara": "bym",
  "barada": "gnl",
  "barna": "bzr",
  "dharumbal": "xgm",
  "gungabula": "gyf",
  "gunggari": "kgl",
  "gunya": "gyy",
  "margany": "zmc",
  "gudjal": "na",
  "gugu badhun": "gdc",
  "warungu": "wrg",
  "mangala": "mem",
  "kukatj": "ggd",
  "mayi-kulan": "xyk",
  "mayi-kutuna": "xmy",
  "mayi-thakurti": "nxn",
  "mayi-yapi": "xyj",
  "galaagu": "kba",
  "kalaamaya": "lkm",
  "mirrniny": "nju",
  "kariyarra": "vka",
  "kurrama": "vku",
  "martuthunira": "vma",
  "ngarla": "nlr",
  "ngarluma": "nrl",
  "nhuwala": "nhf",
  "nyamal": "nly",
  "nyiyaparli": "xny",
  "panyjima": "pnw",
  "yindjibarndi": "yij",
  "wanyjirra": "gue",
  "gurindji": "gue",
  "jaru": "ddj",
  "malngin": "gue",
  "mudburra": "mwd",
  "ngardi": "rxd",
  "ngarinyman": "nbj",
  "walmajarri": "wmt",
  "warlmanpa": "wrl",
  "warlpiri": "wbp",
  "nyawaygi": "nyt",
  "wulguru": "qgu",
  "balardung": "nys",
  "bibbulman": "xbp",
  "goreng": "xgg",
  "kaniyang": "nys",
  "pinjarup": "pnj",
  "wardandi": "wxw",
  "wajuk": "xwj",
  "bandjigali": "bjd",
  "southern paakintyi": "drl",
  "pallanganmiddang": "na",
  "ikarranggal": "ikr",
  "aghu tharnggala": "ggr",
  "awu alaya": "typ",
  "ogh awarrangg": "na",
  "anguthimri": "na",
  "guugu yimidhirr": "kky",
  "muluridji": "vmu",
  "djabugay": "dyy",
  "malthanmungu": "bpt",
  "djangun": "djf",
  "lamalama": "lby",
  "rimanggudinhma": "zmv",
  "wik-ngathan": "wig",
  "ayapathu": "ayd",
  "kugu nganhcara": "wua",
  "kuugu ya'u": "kuy",
  "bakanh": "pkn",
  "umpila": "ump",
  "kok nar": "gko",
  "kurtjar": "gdj",
  "kuthant": "xut",
  "walangama": "na",
  "alngith": "aid",
  "aritinngithigh": "dth",
  "ndra'ngith": "dgt",
  "thaynakwithi": "na",
  "linngithigh": "lnj",
  "luthigh": "na",
  "mbiywom": "na",
  "mpalitjanh": "xpj",
  "ngkoth": "na",
  "uradhi": "amz",
  "angkamuthi": "avm",
  "yadhaykenu": "na",
  "yinwum": "na",
  "koko bera": "kkp",
  "thaayorre": "thd",
  "olkol": "kjn",
  "yir yoront": "yiy",
  "agwamin": "wmi",
  "mbara": "mvl",
  "umbuygamu": "umg",
  "oykangand": "kjn",
  "adnyamathanha": "adt",
  "kaurna": "zku",
  "nukunu": "nnv",
  "wirangu": "wiw",
  "parnkalla": "bjb",
  "narrungga": "nnr",
  "kukata": "ktd",
  "gureng-gureng": "gnr",
  "butchulla": "gbw",
  "gabi-gabi": "gbw",
  "duungidjawu": "wkw",
  "waka waka": "wkw",
  "wuli wuli": "wlu",
  "bularnu": "na",
  "eastern wakaya": "wga",
  "warluwarra": "wrb",
  "warumungu": "wrm",
  "kartujarra": "mpj",
  "manjiljarra": "mpj",
  "putijarra": "mpj",
  "wangkajunga": "mpj",
  "yulparija": "na",
  "warnman": "wbt",
  "kukatja": "kux",
  "ngarlawangka": "nrk",
  "ngaanyatjarra": "ntj",
  "pintupi": "piu",
  "yankunytjatjara": "kdd",
  "kala kawaw ya": "mwp",
  "malyangapa": "yga",
  "wadikali": "wdk",
  "yardliyawarra": "yxl",
  "dhangu": "dhg",
  "gupapuyngu": "guf",
  "dhay'yi": "dax",
  "djambarrpuyngu": "djr",
  "gumatj": "gnn",
  "djinang": "dji",
  "djinba": "djb",
  "nhangu": "jay",
  "ritharrngu": "rit",
  "yabula-yabula": "xyy",
  "bigambal": "xbe",
  "yugambal": "yub",
  "darkinyung": "xda",
  "dharuk": "xdk",
  "awabakal": "awk",
  "katthang": "kda",
  "nganyaywana": "nyx",
  "thanggati": "dyn",
  "djapu": "duj",
  "dharawal": "tbh",
  "dhurga": "dhu",
  "djirringany": "xtv",
  "gundungurra": "xrd",
  "ngarigu": "xni",
  "ngunawal": "na",
  "gangalidda": "gcd",
  "kayardild": "gyd",
  "lardil": "lbz",
  "wagiman": "waq",
  "gambera": "gma",
  "kwini": "gww",
  "wunambal": "wub",
  "umiida": "xud",
  "unggumi": "xgu",
  "worrorra": "wro",
  "yawijibaya": "jbw",
  "wardaman": "wrr",
  "yangman": "jng",
  "guwamu": "gwu",
  "ngardily": "wbp",
  "piangil": "weg"
}

